Revert "Replaced MainView.xib with MainView.storyboard. Reasons:"
This reverts commit 67a3de988832f7ac7be87d3e72f1d0009fb63361.

Couldn't get past crash when loading storyboard:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSINternalInconsistencyException Reason:
Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/...> with name /MainView'

Conflicts:
  CycleTrip/CycleTrip.iOS/Views/MainView.cs